name: Reusable - Build & Push Docker

on:
  workflow_call:
    inputs:
      ref:
        description: "Branch"
        required: false
        default: "main"
      dockerfile:
        description: "Path to Dockerfile"
        required: false
        default: "./Dockerfile"
      context:
        description: "Docker build context"
        required: false
        default: "."
    secrets:
      GHCR_TOKEN:
        required: true
      IMAGE_REPOSITORY:
        description: "GitHub repository path (e.g. org/repo)"
        required: true
      IMAGE_TAG:
        description: "Image name (e.g. latest)"
        required: false

jobs:
  build-docker:
    runs-on: ubuntu-latest

    if: ${{ github.repository == 'szen7dev/trixgo-builds' && github.event_name != 'pull_request' }}

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_REGISTRY: ghcr.io

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.CHECKOUT_REPOSITORY }}
          ref: ${{ github.event.inputs.ref || 'main' }}
          ssh-key: ${{ secrets.CHECKOUT_SSH_KEY }}

      - name: Authenticate with GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}/${{ secrets.IMAGE_REPOSITORY }}:${{ inputs.IMAGE_TAG }}
