name: Reusable - Build & Push Docker

on:
  workflow_call:
    inputs:
      REF:
        description: "Branch"
        required: false
        default: "main"
        type: string
      DOCKER_FILE:
        description: "Path to Dockerfile"
        required: false
        default: "./Dockerfile"
        type: string
      CONTEXT:
        description: "Docker build context"
        required: false
        default: "."
        type: string
    secrets:
      GHCR_TOKEN:
        required: true
      CHECKOUT_REPOSITORY:
        required: false
      CHECKOUT_SSH_KEY:
        required: false
      IMAGE_REPOSITORY:
        description: "GitHub repository path (e.g. org/repo)"
        required: true
      IMAGE_TAG:
        description: "Image name (e.g. latest)"
        required: false

jobs:
  build-docker:
    runs-on: ubuntu-latest

    if: ${{ github.repository == 'szen7dev/trixgo-builds' && github.event_name != 'pull_request' }}

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_REGISTRY: ghcr.io
      DOCKER_BUILD_RECORD_UPLOAD: false

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          repository: ${{ secrets.CHECKOUT_REPOSITORY }}
          ref: ${{ inputs.REF || 'main' }}
          ssh-key: ${{ secrets.CHECKOUT_SSH_KEY }}

      - name: Authenticate with GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.CONTEXT }}
          file: ${{ inputs.DOCKER_FILE }}
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}/${{ secrets.IMAGE_REPOSITORY }}:${{ inputs.IMAGE_TAG }}
