name: Build FE

on:
  workflow_dispatch:
    inputs:
      REF:
        description: "Branch or commit sha"
        required: false
        default: "main"
        type: string
      IMAGE_TAG:
        description: "Image tag"
        required: false
        default: "latest"
        type: string
      DOCKER_FILE:
        description: "Path to Dockerfile"
        required: false
        default: "./Dockerfile"
        type: string
      CONTEXT:
        description: "Docker build context"
        required: false
        default: "."
        type: string

jobs:
  build:
    uses: ./.github/workflows/build-docker.yml
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHECKOUT_REPOSITORY: ${{ secrets.FE_CHECKOUT_REPOSITORY }}
      CHECKOUT_SSH_KEY: ${{ secrets.FE_CHECKOUT_SSH_KEY }}
      IMAGE_REPOSITORY: ${{ secrets.FE_IMAGE_REPOSITORY }}
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
    with:
      REF: ${{ inputs.REF }}
      DOCKER_FILE: ${{ inputs.DOCKER_FILE }}
      CONTEXT: ${{ inputs.CONTEXT }}
